fix: `docs.rs` build failure
See https://docs.rs/crate/object_store/latest/builds/2752265 :

```text
[INFO] [stderr]  Documenting object_store v0.13.0 (/opt/rustwide/workdir)
[INFO] [stderr] error[E0557]: feature has been removed
[INFO] [stderr]   --> src/lib.rs:18:29
[INFO] [stderr]    |
[INFO] [stderr] 18 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
[INFO] [stderr]    |                             ^^^^^^^^^^^^ feature has been removed
[INFO] [stderr]    |
[INFO] [stderr]    = note: removed in 1.92.0; see <https://github.com/rust-lang/rust/pull/138907> for more information
[INFO] [stderr]    = note: merged into `doc_cfg`
[INFO] [stderr]
[INFO] [stderr] error: Compilation failed, aborting rustdoc
[INFO] [stderr]
[INFO] [stderr] For more information about this error, try `rustc --explain E0557`.
[INFO] [stderr] error: could not document `object_store`
```